-- AlterTable
ALTER TABLE "Sale" ADD COLUMN     "amountInWords" TEXT,
ADD COLUMN     "cashierName" TEXT,
ADD COLUMN     "cgstAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "cgstPercent" DOUBLE PRECISION NOT NULL DEFAULT 1.5,
ADD COLUMN     "cinNo" TEXT,
ADD COLUMN     "customerCity" TEXT,
ADD COLUMN     "customerPan" TEXT,
ADD COLUMN     "customerState" TEXT,
ADD COLUMN     "grossAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "gstRate" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "gstType" TEXT,
ADD COLUMN     "igstAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "igstPercent" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "invoiceType" TEXT DEFAULT 'TAX_INVOICE',
ADD COLUMN     "irnNo" TEXT,
ADD COLUMN     "isCustomerCopy" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "lessUrd" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "netPayable" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "offerDiscount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "placeOfSupply" TEXT,
ADD COLUMN     "sgstAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "sgstPercent" DOUBLE PRECISION NOT NULL DEFAULT 1.5,
ADD COLUMN     "storeGst" TEXT,
ADD COLUMN     "subTotal" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "taxableAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "termsAccepted" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "totalTax" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "SaleItem" ADD COLUMN     "hsnCode" TEXT DEFAULT '711319',
ADD COLUMN     "itemCode" TEXT,
ADD COLUMN     "makingChargeRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "makingChargeType" TEXT DEFAULT 'PERCENT',
ADD COLUMN     "otherCharges" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "particulars" TEXT,
ADD COLUMN     "purityName" TEXT;

-- AlterTable
ALTER TABLE "SalePayment" ADD COLUMN     "description" TEXT,
ADD COLUMN     "paymentChannel" TEXT,
ADD COLUMN     "transactionId" TEXT;

-- AlterTable
ALTER TABLE "Store" ADD COLUMN     "address" TEXT,
ADD COLUMN     "cinNo" TEXT,
ADD COLUMN     "city" TEXT,
ADD COLUMN     "gstNo" TEXT,
ADD COLUMN     "phone" TEXT,
ADD COLUMN     "state" TEXT,
ADD COLUMN     "tagline" TEXT,
ADD COLUMN     "termsConditions" TEXT;
